/* eslint-disable @typescript-eslint/no-require-imports */
const fs = require('fs');

const rawPlaces = [
  { name: "Jaffna Fort", district: "Jaffna", category: "Culture", description: "Portuguese & Dutch காலத்தில் கட்டப்பட்ட famous fort. Sea views, old architecture & history loversக்கு attractive tourist spot.", bestTime: "Morning & Evening", image: "https://images.unsplash.com/photo-1579606032822-72b10ccbf319?q=80&w=1000&auto=format&fit=crop" },
  { name: "Casuarina Beach", district: "Jaffna", category: "Beach", description: "Jaffna-வின் clean & shallow beachesல ஒன்று. Swimming, relaxing & family outingக்கு very popular place.", bestTime: "April – September", image: "https://images.unsplash.com/photo-1544644181-1484b3fdfc62?q=80&w=1000&auto=format&fit=crop" },
  { name: "Nagadeepa Purana Viharaya", district: "Jaffna", category: "Religious", description: "Historic Buddhist temple located on an island near Jaffna. Peaceful spiritual atmosphere & boat travel experience காரணமாக tourists visit பண்ணுறாங்க.", bestTime: "Morning Time", image: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?q=80&w=1000&auto=format&fit=crop" },
  { name: "Delft Island", district: "Jaffna", category: "Nature", description: "Wild horses, Dutch historical remains & unique island lifestyle காரணமாக famous tourist destination. Adventure travelers அதிகமாக visit பண்ணுறாங்க.", bestTime: "May – September", image: "https://images.unsplash.com/photo-1589136777351-fdc9c9cb164f?q=80&w=1000&auto=format&fit=crop" },
  { name: "Sigiriya Rock Fortress", district: "Matale", category: "Culture", description: "Sigiriya is one of the most iconic historical attractions in Sri Lanka. This ancient rock fortress was built by King Kashyapa and is famous for its stunning frescoes, mirror wall, lion staircase, and breathtaking panoramic views from the top. It is a UNESCO World Heritage Site and attracts thousands of local and foreign tourists every year.", bestTime: "Early morning to avoid heat and crowds", image: "https://images.unsplash.com/photo-1588598198321-983ce8bc283a?q=80&w=1000&auto=format&fit=crop" },
  { name: "Temple of the Sacred Tooth Relic", district: "Kandy", category: "Religious", description: "The Temple of the Sacred Tooth Relic is one of the most sacred Buddhist temples in the world. Located in the heart of Kandy, the temple houses the sacred tooth relic of Lord Buddha. The beautiful Kandyan architecture, cultural importance, and traditional ceremonies make it a must-visit destination in Sri Lanka.", bestTime: "During the evening pooja (prayer) times", image: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?q=80&w=1000&auto=format&fit=crop" },
  { name: "Nine Arches Bridge", district: "Badulla", category: "Culture", description: "The Nine Arches Bridge is one of the most photographed landmarks in Sri Lanka. Surrounded by lush green tea plantations and forests, this colonial-era railway bridge is famous for its beautiful architecture and scenic train views. Visitors often come here for photography, walking, and relaxing in nature.", bestTime: "When the train is scheduled to pass", image: "https://images.unsplash.com/photo-1565552643952-b43ceb6c3116?q=80&w=1000&auto=format&fit=crop" },
  { name: "Yala National Park", district: "Hambantota", category: "Wildlife", description: "Yala National Park is the most famous wildlife sanctuary in Sri Lanka. It is well known for its leopard population, elephants, sloth bears, crocodiles, and hundreds of bird species. Jeep safari tours give visitors an exciting opportunity to experience Sri Lanka’s wildlife and natural beauty.", bestTime: "February to July during the dry season", image: "https://images.unsplash.com/photo-1610368729606-c8524de4d3ba?q=80&w=1000&auto=format&fit=crop" },
  { name: "Galle Fort", district: "Galle", category: "Culture", description: "Galle Fort is a historic coastal fortress built by the Portuguese and later expanded by the Dutch. The fort is famous for its colonial architecture, charming streets, cafes, museums, and ocean views. It is one of the best places in Sri Lanka for walking tours, photography, and cultural experiences.", bestTime: "Late afternoon to catch the sunset", image: "https://images.unsplash.com/photo-1579606032822-72b10ccbf319?q=80&w=1000&auto=format&fit=crop" },
  { name: "Mirissa Beach", district: "Matara", category: "Beach", description: "Mirissa Beach is one of the most popular beach destinations in Sri Lanka. It is famous for its golden sand, clear blue water, surfing, whale watching tours, and vibrant beach restaurants. The peaceful atmosphere makes it ideal for relaxation and vacations.", bestTime: "November to April for best weather and whale watching", image: "https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?q=80&w=1000&auto=format&fit=crop" },
  { name: "Adam’s Peak", district: "Ratnapura", category: "Adventure", description: "Adam’s Peak is a sacred mountain visited by thousands of pilgrims and tourists every year. The mountain is famous for the “Sri Pada” footprint at the summit and the breathtaking sunrise view. Hiking to the top during the pilgrimage season is a unique and unforgettable experience.", bestTime: "December to May (pilgrimage season)", image: "https://images.unsplash.com/photo-1616422329388-3725f4bbfaec?q=80&w=1000&auto=format&fit=crop" },
  { name: "Horton Plains National Park", district: "Nuwara Eliya", category: "Nature", description: "Horton Plains National Park is a beautiful highland plateau covered with grasslands, forests, and unique wildlife. It is home to famous attractions such as World’s End and Baker’s Falls. The cool climate and scenic hiking trails make it a favorite destination for nature lovers.", bestTime: "Early morning before the mist rolls in (around 6 AM)", image: "https://images.unsplash.com/photo-1589136777351-fdc9c9cb164f?q=80&w=1000&auto=format&fit=crop" },
  { name: "Pinnawala Elephant Orphanage", district: "Kegalle", category: "Wildlife", description: "Pinnawala Elephant Orphanage is one of the most famous wildlife attractions in Sri Lanka. It provides care and protection for orphaned and injured elephants. Visitors can watch elephants being fed, bathing in the river, and moving together in large groups. It is a popular destination for families and animal lovers.", bestTime: "Morning feeding time", image: "https://images.unsplash.com/photo-1583339833502-3c8801f4c7f0?q=80&w=1000&auto=format&fit=crop" },
  { name: "Dambulla Cave Temple", district: "Matale", category: "Religious", description: "Dambulla Cave Temple is the largest and best-preserved cave temple complex in Sri Lanka. The temple contains ancient Buddha statues, beautiful wall paintings, and historic cave shrines. Its cultural value and peaceful atmosphere attract both pilgrims and tourists from around the world.", bestTime: "Early morning or late afternoon", image: "https://images.unsplash.com/photo-1620957961814-747209e2be35?q=80&w=1000&auto=format&fit=crop" },
  { name: "Arugam Bay", district: "Ampara", category: "Beach", description: "Arugam Bay is internationally famous for surfing and beach tourism. The area offers beautiful sandy beaches, surfing waves, seafood restaurants, and a relaxed coastal lifestyle. It is one of the top destinations for adventure travelers and surfers visiting Sri Lanka.", bestTime: "May to September for the best surf conditions", image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1000&auto=format&fit=crop" },
  { name: "Ravana Falls", district: "Badulla", category: "Nature", description: "Ravana Falls is one of the widest and most beautiful waterfalls in Sri Lanka. Surrounded by mountains and greenery, the waterfall is a favorite stop for travelers visiting Ella. The location is ideal for photography, sightseeing, and enjoying nature.", bestTime: "During or just after the rainy season", image: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?q=80&w=1000&auto=format&fit=crop" },
  { name: "Bentota Beach", district: "Galle", category: "Beach", description: "Bentota Beach is one of the most luxurious beach destinations in Sri Lanka. It is well known for golden sandy shores, water sports activities, boat rides, and relaxing resorts. Visitors enjoy jet skiing, banana boat rides, and peaceful sunsets along the coast.", bestTime: "October to April", image: "https://images.unsplash.com/photo-1549471013-3364d7220b7a?q=80&w=1000&auto=format&fit=crop" },
  { name: "Udawalawe National Park", district: "Ratnapura", category: "Wildlife", description: "Udawalawe National Park is famous for its large population of wild elephants and scenic grasslands. Jeep safaris allow visitors to observe elephants, deer, buffaloes, crocodiles, and many bird species in their natural habitat. It is one of the best safari destinations in Sri Lanka.", bestTime: "Early morning or late afternoon", image: "https://images.unsplash.com/photo-1610368729606-c8524de4d3ba?q=80&w=1000&auto=format&fit=crop" },
  { name: "Lipton’s Seat", district: "Badulla", category: "Nature", description: "Lipton’s Seat is a breathtaking viewpoint surrounded by tea plantations and mountain landscapes. It was a favorite observation point of Sir Thomas Lipton, the famous tea planter. Visitors come here to enjoy panoramic views, cool weather, and peaceful natural surroundings.", bestTime: "Early morning before 10 AM", image: "https://images.unsplash.com/photo-1565552643952-b43ceb6c3116?q=80&w=1000&auto=format&fit=crop" },
  { name: "Polonnaruwa Ancient City", district: "Polonnaruwa", category: "Culture", description: "Polonnaruwa Ancient City is one of the most important archaeological sites in Sri Lanka. The city contains ancient temples, royal palaces, statues, and historic ruins from the medieval Sinhalese kingdom. It is a must-visit destination for history and culture enthusiasts.", bestTime: "Early morning to explore the ruins before it gets too hot", image: "https://images.unsplash.com/photo-1616422329388-3725f4bbfaec?q=80&w=1000&auto=format&fit=crop" },
  { name: "Trincomalee Beach", district: "Trincomalee", category: "Beach", description: "Trincomalee Beach is famous for its crystal-clear blue water, soft white sand, and calm atmosphere. It is an ideal destination for swimming, relaxing, snorkeling, and family vacations. The beach is also popular for whale watching and sunrise views.", bestTime: "May to October for calm seas", image: "https://images.unsplash.com/photo-1544644181-1484b3fdfc62?q=80&w=1000&auto=format&fit=crop" },
  { name: "Rumassala Sanctuary", district: "Galle", category: "Nature", description: "Rumassala Sanctuary is a beautiful coastal forest area associated with the Ramayana legend. The sanctuary offers hiking paths, ocean viewpoints, rich biodiversity, and peaceful natural surroundings. It is popular for nature walks, photography, and scenic sunset views.", bestTime: "Early morning or late afternoon", image: "https://images.unsplash.com/photo-1589136777351-fdc9c9cb164f?q=80&w=1000&auto=format&fit=crop" },
  { name: "Nilaveli Beach", district: "Trincomalee", category: "Beach", description: "Nilaveli Beach is one of the cleanest and most peaceful beaches in Sri Lanka. The shallow blue waters and quiet surroundings make it perfect for relaxation, swimming, and beachside holidays. It is also a gateway to Pigeon Island National Park.", bestTime: "May to October", image: "https://images.unsplash.com/photo-1544644181-1484b3fdfc62?q=80&w=1000&auto=format&fit=crop" },
  { name: "Pigeon Island National Park", district: "Trincomalee", category: "Nature", description: "Pigeon Island National Park is one of Sri Lanka’s most beautiful marine parks. It is famous for snorkeling, coral reefs, colorful fish, and blacktip reef sharks. Visitors can enjoy boat rides, underwater exploration, and tropical island scenery.", bestTime: "May to October", image: "https://images.unsplash.com/photo-1583339833502-3c8801f4c7f0?q=80&w=1000&auto=format&fit=crop" },
  { name: "Koneswaram Temple", district: "Trincomalee", category: "Religious", description: "Koneswaram Temple is a famous Hindu temple located on Swami Rock overlooking the Indian Ocean. The temple is known for its spiritual atmosphere, colorful architecture, and breathtaking sea views. It is one of the most important religious sites in Sri Lanka.", bestTime: "Early morning for sunrise", image: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?q=80&w=1000&auto=format&fit=crop" },
  { name: "Anuradhapura Sacred City", district: "Anuradhapura", category: "Culture", description: "Anuradhapura Sacred City is one of the oldest and most important ancient capitals in Sri Lanka. The city is filled with massive stupas, ancient monasteries, sacred temples, and archaeological ruins. It is also home to the sacred Sri Maha Bodhi tree, which is believed to be the oldest historically documented tree in the world.", bestTime: "Early morning or late afternoon", image: "https://images.unsplash.com/photo-1620957961814-747209e2be35?q=80&w=1000&auto=format&fit=crop" },
  { name: "Mihintale", district: "Anuradhapura", category: "Religious", description: "Mihintale is considered the birthplace of Buddhism in Sri Lanka. The mountain area contains ancient temples, stone stairways, stupas, and panoramic viewpoints. Visitors climb the famous staircase to enjoy spiritual surroundings and scenic views.", bestTime: "Early morning or late afternoon", image: "https://images.unsplash.com/photo-1620957961814-747209e2be35?q=80&w=1000&auto=format&fit=crop" },
  { name: "Wilpattu National Park", district: "Anuradhapura", category: "Wildlife", description: "Wilpattu National Park is the largest national park in Sri Lanka and is famous for its leopard population, natural lakes, and dense forests. Jeep safaris offer opportunities to spot elephants, sloth bears, deer, crocodiles, and many bird species.", bestTime: "February to October", image: "https://images.unsplash.com/photo-1610368729606-c8524de4d3ba?q=80&w=1000&auto=format&fit=crop" },
  { name: "Ruwanwelisaya", district: "Anuradhapura", category: "Religious", description: "Ruwanwelisaya is one of the most sacred and magnificent stupas in Sri Lanka. Built by King Dutugemunu, the white dome-shaped stupa attracts thousands of Buddhist pilgrims and tourists every year. The peaceful atmosphere and impressive architecture make it a remarkable spiritual destination.", bestTime: "Early morning or evening for pooja", image: "https://images.unsplash.com/photo-1620957961814-747209e2be35?q=80&w=1000&auto=format&fit=crop" },
  { name: "Sinharaja Forest Reserve", district: "Ratnapura", category: "Nature", description: "Sinharaja Forest Reserve is the last major tropical rainforest in Sri Lanka and a UNESCO World Heritage Site. The forest is rich in biodiversity and home to rare birds, butterflies, reptiles, and endemic wildlife species. Nature lovers and hikers visit this rainforest to experience waterfalls, dense jungle paths, and untouched natural beauty.", bestTime: "August to September or December to early April", image: "https://images.unsplash.com/photo-1589136777351-fdc9c9cb164f?q=80&w=1000&auto=format&fit=crop" },
  { name: "Bambarakanda Falls", district: "Badulla", category: "Nature", description: "Bambarakanda Falls is the tallest waterfall in Sri Lanka, surrounded by pine forests and mountain scenery. Visitors enjoy hiking trails, photography, and the cool natural environment around the waterfall. It is a popular destination for adventure travelers and nature enthusiasts.", bestTime: "During or just after the rainy season", image: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?q=80&w=1000&auto=format&fit=crop" },
  { name: "Knuckles Mountain Range", district: "Matale", category: "Adventure", description: "The Knuckles Mountain Range is one of Sri Lanka’s most scenic hiking destinations. Covered with forests, waterfalls, cloud-covered mountains, and rich biodiversity, the area is perfect for trekking, camping, and outdoor adventures. The breathtaking landscapes attract both local and foreign travelers.", bestTime: "June to September", image: "https://images.unsplash.com/photo-1616422329388-3725f4bbfaec?q=80&w=1000&auto=format&fit=crop" },
  { name: "Baker’s Falls", district: "Nuwara Eliya", category: "Nature", description: "Baker’s Falls is a beautiful waterfall located within Horton Plains National Park. Surrounded by green forests and misty hills, it is one of the most visited natural attractions in the central highlands of Sri Lanka. The area is popular for hiking, photography, and nature exploration.", bestTime: "Early morning", image: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?q=80&w=1000&auto=format&fit=crop" },
  { name: "Ella Rock", district: "Badulla", category: "Adventure", description: "Ella Rock is one of the most popular hiking destinations in Sri Lanka. The trail passes through tea plantations, railway tracks, forests, and scenic mountain paths. The summit offers breathtaking panoramic views of valleys, hills, and surrounding countryside, making it a favorite spot for hikers and photographers.", bestTime: "Early morning to avoid afternoon mist", image: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?q=80&w=1000&auto=format&fit=crop" },
  { name: "Little Adam’s Peak", district: "Badulla", category: "Nature", description: "Little Adam’s Peak is a scenic hilltop viewpoint known for its easy hiking trail and stunning mountain views. Visitors can enjoy green tea plantations, cool weather, sunrise photography, and relaxing walks along the hillside paths. It is one of the best beginner-friendly hiking spots in Ella.", bestTime: "Early morning or late afternoon", image: "https://images.unsplash.com/photo-1565552643952-b43ceb6c3116?q=80&w=1000&auto=format&fit=crop" },
  { name: "Gregory Lake", district: "Nuwara Eliya", category: "Nature", description: "Gregory Lake is a popular recreational destination surrounded by cool mountain scenery. Visitors enjoy boat rides, cycling, horse riding, food stalls, and relaxing walks around the lake. The peaceful atmosphere makes it ideal for families and couples.", bestTime: "April during the Nuwara Eliya season", image: "https://images.unsplash.com/photo-1625736194788-b2a0c647b7ba?q=80&w=1000&auto=format&fit=crop" },
  { name: "Seetha Amman Temple", district: "Nuwara Eliya", category: "Religious", description: "Seetha Amman Temple is a famous Hindu temple connected to the Ramayana legend. According to tradition, this is believed to be the place where Princess Sita was kept during her captivity by King Ravana. The temple is surrounded by rivers, forests, and beautiful hill country scenery.", bestTime: "Morning or evening pooja times", image: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?q=80&w=1000&auto=format&fit=crop" },
  { name: "Minneriya National Park", district: "Polonnaruwa", category: "Wildlife", description: "Minneriya National Park is world famous for “The Gathering,” one of the largest gatherings of wild elephants in Asia. During the dry season, hundreds of elephants gather around the Minneriya reservoir. The park is also home to deer, monkeys, crocodiles, and many bird species, making it an excellent safari destination.", bestTime: "July to October", image: "https://images.unsplash.com/photo-1583339833502-3c8801f4c7f0?q=80&w=1000&auto=format&fit=crop" },
  { name: "Pidurangala Rock", district: "Matale", category: "Adventure", description: "Pidurangala Rock is a popular hiking destination located near Sigiriya. The summit offers spectacular panoramic views of Sigiriya Rock Fortress, forests, and surrounding landscapes. The hiking trail includes rocky paths, ancient temple areas, and breathtaking sunrise viewpoints.", bestTime: "Early morning for sunrise", image: "https://images.unsplash.com/photo-1588598198321-983ce8bc283a?q=80&w=1000&auto=format&fit=crop" },
  { name: "Kalpitiya Beach", district: "Puttalam", category: "Beach", description: "Kalpitiya Beach is one of the best kitesurfing and dolphin-watching destinations in Sri Lanka. The coastal area is famous for its lagoons, strong winds, marine life, and peaceful beaches. Adventure travelers visit Kalpitiya for water sports, boat tours, and relaxing beach holidays.", bestTime: "November to March for dolphins, May to October for kitesurfing", image: "https://images.unsplash.com/photo-1544644181-1484b3fdfc62?q=80&w=1000&auto=format&fit=crop" },
  { name: "Gangaramaya Temple", district: "Colombo", category: "Religious", description: "Gangaramaya Temple is one of the most famous Buddhist temples in Colombo. The temple combines Sri Lankan, Thai, Indian, and Chinese architectural styles and includes a museum, library, statues, and sacred religious artifacts. It is a major spiritual and cultural attraction visited by both locals and tourists.", bestTime: "Any time of day", image: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?q=80&w=1000&auto=format&fit=crop" },
  { name: "Viharamahadevi Park", district: "Colombo", category: "Nature", description: "Viharamahadevi Park is the largest public park in Colombo and a popular recreational destination for families and children. The park features walking paths, fountains, playgrounds, gardens, and relaxing green spaces in the middle of the city.", bestTime: "Early morning or late afternoon", image: "https://images.unsplash.com/photo-1589136777351-fdc9c9cb164f?q=80&w=1000&auto=format&fit=crop" },
  { name: "Lotus Tower", district: "Colombo", category: "Culture", description: "Lotus Tower is the tallest tower in South Asia and one of the most modern landmarks in Sri Lanka. The tower offers panoramic views of Colombo city, restaurants, entertainment areas, and observation decks. It is especially popular for night views and photography.", bestTime: "Late afternoon to evening for city lights", image: "https://images.unsplash.com/photo-1625736194788-b2a0c647b7ba?q=80&w=1000&auto=format&fit=crop" },
  { name: "Galle Face Green", district: "Colombo", category: "Beach", description: "Galle Face Green is a famous oceanfront urban park located along the coast of Colombo. Visitors enjoy street food, kite flying, sunset views, jogging, and relaxing by the sea. It is one of the busiest and most iconic public gathering places in the city.", bestTime: "Late afternoon for sunset and street food", image: "https://images.unsplash.com/photo-1544644181-1484b3fdfc62?q=80&w=1000&auto=format&fit=crop" },
  { name: "Hikkaduwa Beach", district: "Galle", category: "Beach", description: "Hikkaduwa Beach is one of the most vibrant beach destinations in Sri Lanka. It is famous for surfing, snorkeling, coral reefs, beach parties, seafood restaurants, and lively nightlife. The beach attracts both local and international tourists throughout the year.", bestTime: "November to April", image: "https://images.unsplash.com/photo-1574005085876-0f7011cc0a12?q=80&w=1000&auto=format&fit=crop" },
  { name: "Unawatuna Beach", district: "Galle", category: "Beach", description: "Unawatuna Beach is known for its calm blue waters, golden sand, and tropical atmosphere. It is a perfect destination for swimming, snorkeling, beachside dining, and relaxing holidays. The beach is surrounded by hotels, cafes, and palm trees, creating a peaceful vacation environment.", bestTime: "November to April", image: "https://images.unsplash.com/photo-1549471013-3364d7220b7a?q=80&w=1000&auto=format&fit=crop" },
  { name: "Jungle Beach", district: "Galle", category: "Beach", description: "Jungle Beach is a hidden tropical beach surrounded by forest and hills near Unawatuna. The beach offers a peaceful environment for swimming, snorkeling, sunbathing, and nature photography. Its quiet atmosphere makes it a favorite location for travelers seeking relaxation away from crowded areas.", bestTime: "Early morning to avoid crowds", image: "https://images.unsplash.com/photo-1544644181-1484b3fdfc62?q=80&w=1000&auto=format&fit=crop" },
  { name: "Pasikuda Beach", district: "Batticaloa", category: "Beach", description: "Pasikuda Beach is famous for its shallow turquoise waters and long sandy coastline. The calm sea conditions make it one of the safest beaches in Sri Lanka for swimming and family vacations. Visitors enjoy water sports, beach resorts, and peaceful ocean views.", bestTime: "May to September", image: "https://images.unsplash.com/photo-1544644181-1484b3fdfc62?q=80&w=1000&auto=format&fit=crop" },
  { name: "Batticaloa Lagoon", district: "Batticaloa", category: "Nature", description: "Batticaloa Lagoon is a large scenic lagoon known for its peaceful atmosphere and beautiful sunsets. Visitors can enjoy boat rides, bird watching, fishing activities, and relaxing views of the surrounding mangroves and waterways.", bestTime: "Late afternoon for sunset", image: "https://images.unsplash.com/photo-1589136777351-fdc9c9cb164f?q=80&w=1000&auto=format&fit=crop" },
  { name: "Batticaloa Fort", district: "Batticaloa", category: "Culture", description: "Batticaloa Fort is a historic fortress originally built by the Portuguese and later developed by the Dutch. The fort is surrounded by the lagoon and features colonial architecture, old walls, and scenic viewpoints. It is a popular attraction for history lovers and photographers.", bestTime: "Late afternoon", image: "https://images.unsplash.com/photo-1579606032822-72b10ccbf319?q=80&w=1000&auto=format&fit=crop" }
];

const latLongMap = {
  "Colombo": { lat: 6.9271, lng: 79.8612 },
  "Jaffna": { lat: 9.6615, lng: 80.0255 },
  "Kandy": { lat: 7.2906, lng: 80.6337 },
  "Galle": { lat: 6.0328, lng: 80.2168 },
  "Matara": { lat: 5.9549, lng: 80.5470 },
  "Badulla": { lat: 6.9880, lng: 81.0560 },
  "Nuwara Eliya": { lat: 6.9497, lng: 80.7828 },
  "Ratnapura": { lat: 6.7056, lng: 80.3847 },
  "Anuradhapura": { lat: 8.3114, lng: 80.4037 },
  "Polonnaruwa": { lat: 7.9403, lng: 81.0188 },
  "Matale": { lat: 7.4675, lng: 80.6234 },
  "Trincomalee": { lat: 8.5875, lng: 81.2152 },
  "Batticaloa": { lat: 7.7102, lng: 81.6924 },
  "Ampara": { lat: 7.2885, lng: 81.6747 },
  "Hambantota": { lat: 6.1248, lng: 81.1221 },
  "Kegalle": { lat: 7.2513, lng: 80.3464 },
  "Puttalam": { lat: 8.0362, lng: 79.8283 }
};

const provinceMap = {
  "Colombo": "Western Province",
  "Jaffna": "Northern Province",
  "Kandy": "Central Province",
  "Galle": "Southern Province",
  "Matara": "Southern Province",
  "Badulla": "Uva Province",
  "Nuwara Eliya": "Central Province",
  "Ratnapura": "Sabaragamuwa Province",
  "Anuradhapura": "North Central Province",
  "Polonnaruwa": "North Central Province",
  "Matale": "Central Province",
  "Trincomalee": "Eastern Province",
  "Batticaloa": "Eastern Province",
  "Ampara": "Eastern Province",
  "Hambantota": "Southern Province",
  "Kegalle": "Sabaragamuwa Province",
  "Puttalam": "North Western Province"
};

const formattedPlaces = rawPlaces.map((p, index) => {
  const loc = latLongMap[p.district] || { lat: 7.8731, lng: 80.7718 };
  const province = provinceMap[p.district] || "Unknown Province";
  
  return `  {
    id: 'p${index + 100}',
    name: '${p.name.replace(/'/g, "\\'")}',
    province: '${province}',
    district: '${p.district.replace(/'/g, "\\'")}',
    category: '${p.category}',
    description: '${p.description.replace(/'/g, "\\'")}',
    image: '${p.image}',
    rating: ${(Math.random() * (5.0 - 4.2) + 4.2).toFixed(1)},
    bestTimeToVisit: '${p.bestTime.replace(/'/g, "\\'")}',
    nearbyAttractions: [],
    tags: ['${p.category}'],
    latitude: ${loc.lat + (Math.random() * 0.1 - 0.05)},
    longitude: ${loc.lng + (Math.random() * 0.1 - 0.05)}
  }`;
});

const output = `import { Place } from '@/lib/types';

export const places: Place[] = [
${formattedPlaces.join(',\n')}
];
`;

fs.writeFileSync('/Users/kapilash/Documents/kkapilashtourist/src/data/places.ts', output);
console.log('Successfully generated places.ts with ' + formattedPlaces.length + ' places.');
